### ISSUE TITLE
Belgian prices?

### ISSUE THREAD

**Issue by liviooo** [Hexagon/spotweb#10]
Can you add the BE (Belgian) prices too ?

**Comment by Hexagon** [comment]
Will have a look at that :+1:

**Comment by Hexagon** [comment]
Belgien is included now, but it will take up to 12 hours before it has complete data. Ill leave this issue open for you to verify when/if everything looks good.

**Comment by Hexagon** [comment]
Also verify if correct language is shown for you on the site?

**Comment by liviooo** [comment]
Thank you. Seems to work. Translations to Dutch are done (see email).
