### ISSUE TITLE
Other way of calculation of the prices

### ISSUE THREAD

**Issue by liviooo** [Hexagon/spotweb#11]
Our Belgian energy company ECOPOWER uses a different way of calculating the prices:
1,02 * (EPEX DA) + 4 euro/MWh + 6% VAT + (5 euro's fee per month)

Thus the calculation should be: ((EPEX DA) x 1,02) + 0,004) x 1,06

The current way of price calculation (ex vat) is as follows:
((EPEX DA) + 0,004) x 1,02

Any chance we can have extra fields for extra costs and a different way of calculating totals?

**Comment by Hexagon** [comment]
Interesting! Will have a look at that

**Comment by Hexagon** [comment]
@liviooo Now multiplier is added, and have started writing more about calculation on <https://spot.56k.guru/help>

Also added your dutch translation (will be used if your computer is set to dutch).

Would be great if you can verify that it works as expected 👀

**Comment by liviooo** [comment]
I did a quick calculation, but the figures don't match yet.

Manual calculation: ((0,1157*1,02)+0,004)*1,06= **0,1293** €/kWh inc. VAT

The URL: https://spot.56k.guru/api/v2/hass?currency=EUR&area=BE&multiplier=1.2&extra=0.004&factor=1.06&decimals=4 gives me **0,1514** €/kWh inc. VAT

<img width="260" alt="Screenshot 2023-08-30 at 18 47 10" src="https://github.com/Hexagon/spotweb/assets/23534/c82b2cae-90f5-4524-afed-8cbd9c0ae668">
<img width="472" alt="Screenshot 2023-08-30 at 18 46 46" src="https://github.com/Hexagon/spotweb/assets/23534/4b0cf038-ebd0-4831-a602-d0d4045bcfcb">

**Comment by Hexagon** [comment]
Did a quick check, and it seems like you accidentaly entered `&multiplier=1.2` instead of `&multiplier=1.02`, after fixing that everything seems good :)

**Comment by liviooo** [comment]
Damn, my bad!
