### ISSUE TITLE
Check and correct Norwegian translation

### ISSUE THREAD

**Issue by Hexagon** [Hexagon/spotweb#4]
The site is currently translated using Google Translate. Someone who actually speak norwegian should check and correct [/config/translations/no.js](https://github.com/Hexagon/spotweb/blob/main/config/translations/no.js)

Any part of the site can be seen in Norwegian, either if your computer is set to Norwegian, or by supplying `?lang=no` at the end of any url.

[https://spot.56k.guru/no/NO1?lang=no](https://spot.56k.guru/no/NO1?lang=no)

Pull requests welcome 🥇  Or just comment on fixes below 👍

**Comment by MagnusFagerli** [comment]
Hello! I have taken a look at the norwegian translation file.

I would suggest a minor fix to (snippet below is edited):
```
"actual_price_text":
        "Du har for øyeblikket faktisk strømpris aktivert, men har ikke valgt noen innstillinger for skatter og avgifter. Klikk på hamburgermenyen og fyll inn faktoren (f.eks. 1,25 for 25 % mva) og kostnaden din (f.eks. 0,012 for 0,012 NOK/kWh før mva)."
```
Other than that I find that everything makes sense.

**Comment by Hexagon** [comment]
Cool, thanks! :+1:

**Comment by Hexagon** [comment]
Done
